name: Release Publish

on:
  release:
    types: published

jobs:
  publish:
    name: Set Version, Build & Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"

      - name: Set package version from GitHub tag
        run: |
          TAG_NAME=${GITHUB_REF##*/}
          echo "Setting version to $TAG_NAME"
          bun version "$TAG_NAME"

      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun run build

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          bun config set registry https://registry.npmjs.org/
          bun publish --access public --no-git-checks
