name: Release Publish

on:
  release:
    types: [published]

jobs:
  publish:
    name: Set Version, Build & Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # ensure we have all tags so npm version sees your tag
          fetch-depth: 0

      - name: Configure Git user for version commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Node (for npm)
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: Set package version from GitHub tag
        run: |
          TAG_NAME=${GITHUB_REF##*/}
          echo "Setting version to $TAG_NAME"
          if git rev-parse -q --verify "refs/tags/$TAG_NAME" >/dev/null; then
            echo "Tag $TAG_NAME already exists — skipping npm version"
          else
            npm version "$TAG_NAME"
          fi

      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun run build

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          bun config set registry https://registry.npmjs.org/
          bun publish --access public
